# tasks file for roletest

- name: Get disk facts
  win_disk_facts:

- name: Output first disk size
  debug:
    var: ansible_facts.disks[0].size

- name: Initialize Disk    
  win_shell: Initialize-Disk -Number 1
  when: ansible_disks[1].guid is none

- name: Create a partition with drive letter D and size 5 GiB
  win_partition:
    drive_letter: D
    partition_size: -1
    disk_number: 1
